version: "3.4"

volumes:
  mvn:

services:
  apigateway:
    build:
      args:
        - MODULE_NAME=apigateway
      context: ./backend
      dockerfile: ./issues-tracker/Dockerfile
    command: sh issues-tracker/entrypoint.sh
    environment:
      - MODULE_NAME=apigateway
      - SERVICE_APIGATEWAY_NAME=APIGATEWAY
      - SERVICE_APIGATEWAY_PORT=80
      - SERVICE_DISCOVERY_ZONE=http://discovery:8761/eureka
      - SERVICE_ISSUES_COMMAND_NAME=ISSUES-COMMAND
      - SERVICE_ISSUES_QUERY_NAME=ISSUES-QUERY
      - SERVICE_NOTIFICATIONS_NAME=NOTIFICATIONS
      - SERVICE_ORGANIZATIONS_COMMAND_NAME=ORGANIZATIONS-COMMAND
      - SERVICE_ORGANIZATIONS_QUERY_NAME=ORGANIZATIONS-QUERY
      - SERVICE_USERS_COMMAND_NAME=USERS-COMMAND
      - SERVICE_USERS_QUERY_NAME=USERS-QUERY  
    volumes:
      - ./backend:/usr/src/app
      - mvn:/usr/mvn
  discovery:
    build:
      args:
        - MODULE_NAME=discovery
      context: ./backend
      dockerfile: ./issues-tracker/Dockerfile
    command: sh issues-tracker/entrypoint.sh
    environment:
      - MODULE_NAME=discovery
      - SERVICE_DISCOVERY_PORT=8761
    volumes:
      - ./backend:/usr/src/app
      - mvn:/usr/mvn
  issues-command:
    build:
      args:
        - MODULE_NAME=issues/command
      context: ./backend
      dockerfile: ./issues-tracker/Dockerfile
    command: sh issues-tracker/entrypoint.sh
    depends_on:
      - issues-command-mongo
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MODULE_NAME=issues/command
      - SERVICE_DISCOVERY_ZONE=http://discovery:8761/eureka
      - SERVICE_ISSUES_COMMAND_MONGO_HOST=issues-command-mongo
      - SERVICE_ISSUES_COMMAND_NAME=ISSUES-COMMAND
    volumes:
      - ./backend:/usr/src/app
      - mvn:/usr/mvn
  issues-command-mongo:
    image: mongo:5.0.7
    volumes:
      - /data/db
  issues-query:
    build:
      args:
        - MODULE_NAME=issues/query
      context: ./backend
      dockerfile: ./issues-tracker/Dockerfile
    command: sh issues-tracker/entrypoint.sh
    depends_on:
      - issues-query-mongo
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MODULE_NAME=issues/query
      - SERVICE_DISCOVERY_ZONE=http://discovery:8761/eureka
      - SERVICE_ISSUES_QUERY_MONGO_HOST=issues-query-mongo
      - SERVICE_ISSUES_QUERY_NAME=ISSUES-QUERY
      - SERVICE_NOTIFICATIONS_NAME=NOTIFICATIONS
    volumes:
      - ./backend:/usr/src/app
      - mvn:/usr/mvn
  issues-query-mongo:
    image: mongo:5.0.7
    volumes:
      - /data/db
  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
  kafka:
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    image: bitnami/kafka
    restart: always
  mailhog:
    environment:
      MH_UI_WEB_PATH: mailhog
    image: mailhog/mailhog
  nginx:
    build:
      context: nginx
    depends_on:
      - apigateway
    ports:
      - 80:80
  notifications:
    build:
      args:
        - MODULE_NAME=notifications
      context: ./backend
      dockerfile: ./issues-tracker/Dockerfile
    command: sh issues-tracker/entrypoint.sh
    depends_on:
      - notifications-mongo
      - kafka
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
      - MODULE_NAME=notifications
      - SERVICE_DISCOVERY_ZONE=http://discovery:8761/eureka
      - SERVICE_NOTIFICATIONS_MONGO_HOST=notifications-mongo
      - SERVICE_NOTIFICATIONS_NAME=NOTIFICATIONS
    volumes:
      - ./backend:/usr/src/app
      - mvn:/usr/mvn
  notifications-mongo:
    image: mongo:5.0.7
    volumes:
      - /data/db
  organizations-command:
    build:
      args:
        - MODULE_NAME=organizations/command
      context: ./backend
      dockerfile: ./issues-tracker/Dockerfile
    command: sh issues-tracker/entrypoint.sh
    depends_on:
      - kafka
      - organizations-command-mongo
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MODULE_NAME=organizations/command
      - SERVICE_DISCOVERY_ZONE=http://discovery:8761/eureka
      - SERVICE_ORGANIZATIONS_COMMAND_MONGO_HOST=organizations-command-mongo
      - SERVICE_ORGANIZATIONS_COMMAND_NAME=ORGANIZATIONS-COMMAND
    volumes:
      - ./backend:/usr/src/app
      - mvn:/usr/mvn
  organizations-command-mongo:
    image: mongo:5.0.7
    volumes:
      - /data/db
  organizations-query:
    build:
      args:
        - MODULE_NAME=organizations/query
      context: ./backend
      dockerfile: ./issues-tracker/Dockerfile
    command: sh issues-tracker/entrypoint.sh
    depends_on:
      - kafka
      - organizations-query-mongo
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MODULE_NAME=organizations/query
      - SERVICE_DISCOVERY_ZONE=http://discovery:8761/eureka
      - SERVICE_NOTIFICATIONS_NAME=NOTIFICATIONS
      - SERVICE_ORGANIZATIONS_QUERY_MONGO_HOST=organizations-query-mongo
      - SERVICE_ORGANIZATIONS_QUERY_NAME=ORGANIZATIONS-QUERY
    volumes:
      - ./backend:/usr/src/app
      - mvn:/usr/mvn
  organizations-query-mongo:
    image: mongo:5.0.7
    volumes:
      - /data/db
  swagger:
    image: swaggerapi/swagger-ui
    volumes:
        - ./swagger:/usr/share/nginx/html/doc
    environment:
        API_URL: doc/openapi.yml
  users-command:
    build:
      args:
        - MODULE_NAME=users/command
      context: ./backend
      dockerfile: ./issues-tracker/Dockerfile
    command: sh issues-tracker/entrypoint.sh
    depends_on:
      - kafka
      - users-command-mongo
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MODULE_NAME=users/command
      - SERVICE_DISCOVERY_ZONE=http://discovery:8761/eureka
      - SERVICE_USERS_COMMAND_MONGO_HOST=users-command-mongo
      - SERVICE_USERS_COMMAND_NAME=USERS-COMMAND
    volumes:
      - ./backend:/usr/src/app
      - mvn:/usr/mvn
  users-command-mongo:
    image: mongo:5.0.7
    volumes:
      - /data/db
  users-query:
    build:
      args:
        - MODULE_NAME=users/query
      context: ./backend
      dockerfile: ./issues-tracker/Dockerfile
    command: sh issues-tracker/entrypoint.sh
    depends_on:
      - kafka
      - users-query-mongo
    environment:
      - JWT_SECRET=some-jwt-secret
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - MODULE_NAME=users/query
      - SERVICE_DISCOVERY_ZONE=http://discovery:8761/eureka
      - SERVICE_USERS_QUERY_MONGO_HOST=users-query-mongo
      - SERVICE_USERS_QUERY_NAME=USERS-QUERY
    volumes:
      - ./backend:/usr/src/app
      - mvn:/usr/mvn
  users-query-mongo:
    image: mongo:5.0.7
    volumes:
      - /data/db
  zookeeper:
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    image: bitnami/zookeeper
